### ISSUE TITLE
Params tab isn't displaying stylized map

### ISSUE THREAD

**Issue by nathanbiller** [atishay/hugo-debug-utils#1]
The Overview and Site tabs are displaying nicely stylized data, but the Params tab and the Params line on the Site tab are just showing a string of data instead of the nicely laid out example at https://hugo-debug-bar.netlify.app/
![screenshot](https://user-images.githubusercontent.com/13682301/176353470-00d8bb91-be5b-4e96-a93e-838e6a811ca7.jpg)

**Comment by atishay** [comment]
We will have to update the version of the debug bar in this extension.
